### ISSUE TITLE
Say TTS relaunch radio not work

### ISSUE THREAD

**Issue by ADN182** [jishi/node-sonos-http-api#194] opened 2016-04-28 04:38 UTC
Hi,

Thank for this api.

Issue : When i launch tts when radio tune in playing the radio does not play agian after tss (launch TTS twice instead of play tune in radio)

With dezeer song i have no problem.

Best Regards

**Comment by jishi** [comment] 2016-04-28 07:20
Duplicate of https://github.com/jishi/node-sonos-http-api/issues/56

**Closed by jishi** 2016-04-28 07:20 UTC
