### ISSUE TITLE
weird anomoly using the sonos-http-api

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#343] opened 2016-10-14 18:25 UTC
HI,
I have the api running on a pi and its working very well.

I have one player that won't pause for longer than a few seconds - its a ZP90/Connect
If I pause it while playing a track or a radio station it will restart playing after a few seconds
If it has no radio station or track selected it doesn't start by itself.

I thought it was the player so I unplugged it for a few mins and still the same

If I power down the pi (running the api) it will pause and play as one would expect
If I pause the player with the pi off and then power it back on, the player starts playing when the api service starts...

So I thought I have a stray api command that I can't find so I renamed the player to render any of these api command non-functional 

.. but this hasn't made any difference.. my gremlin still exists

anything else I could try ?

Thanks
-f

**Comment by jishi** [comment] 2016-10-14 19:40
Hm, that sounds very odd. If you are able to start the api with NODE_LOG_LEVEL=trace I think it would print out all commands that it actually invokes and would give a hint on whats going on.

basically, manually start the api (stop the autostarted one to begin with) then from the http-api folder (via ssh session) start it with:

`NODE_LOG_LEVEL=trace npm start > debug.log`

keep it open, then reproduce this gremlin behavior. After you have done that, email me that debug.log file that has been created in the same folder.

Renaming the player wouldn't have any effect if the http-api wasn't restarted afterwards, since it will remember the name (and associate it with an IP).

**Comment by autofrank** [comment] 2016-10-14 22:27
thanks, i'll give that a go....

**Comment by jishi** [comment] 2016-11-01 17:58
Closing until feedback arrives

**Closed by jishi** 2016-11-01 17:58 UTC
