### ISSUE TITLE
Sleep and Repeat All in preset doesn't work

### ISSUE THREAD

**Issue by naixra** [jishi/node-sonos-http-api#340] opened 2016-10-11 14:44 UTC
Hello,

Here my preset file : 

`{
  "players": [
    {
      "roomName": "Chambre",
      "volume": 2
    }
    
  ],
  "favorite": "Dodo",
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": true,
    "sleep": 7200
  },
  "pauseOthers": true
}
`

I would like it play "Dodo" in favorite Sonos, during 7200 seconds before stop (sleep) and repeat All songs.

Everything work but not "repeat all" and "sleep after x seconds".

When I restart server.js I get this : 

`16:16:51 medianucenter-desktop node[6889]:      playMode: { shuffle: true, repeat: 'all', crossfade: true, sleep: 7200 },`

There are {sleep : 7200 and repeat : "all" } in log but no effect on the Sonos.

Thanks you.

**Comment by jishi** [comment] 2016-10-11 14:51
sleep goes outside of the playMode block, only repeat, shuffle and crossfade should be in there.

Odd that repeat doesn't work. What kind of source is the favorite "Dodo"?

**Comment by naixra** [comment] 2016-10-11 15:04
"Dodo" is a "Sonos playlist" that I added to Sonos favorite.

Can I play directly one of my Sonos Playlist instead of favorite?

Because I have to add my playlist to favorite in order to add in preset file.

**Comment by jishi** [comment] 2016-10-11 15:21
Yes, you can specify playlist instead of favorite:

```
{
  "players": [
    {
      "roomName": "Chambre",
      "volume": 2
    }
  ],
  "playlist": "Dodo",
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": true
  },
  "sleep": 7200,
  "pauseOthers": true
}
```

**Comment by jishi** [comment] 2016-10-11 15:23
I will have to check when I get home. Or, if you want to troubleshoot, start the server with this:

`NODE_LOG_LEVEL=debug npm start`

And show the output from the console after invoking the preset.

**Comment by naixra** [comment] 2016-10-11 15:51
I get this 

`2016-10-11T15:46:12.811Z DEBUG clearing queue
2016-10-11T15:46:12.889Z DEBUG Adding file:///jffs/settings/savedqueues.rsq#2 to queue
2016-10-11T15:46:13.191Z DEBUG triggering queue mode
2016-10-11T15:46:13.192Z DEBUG setting AVTransport to x-rincon-queue:RINCON_5CAAFD43EB7C01400#0 
2016-10-11T15:46:13.277Z DEBUG invoking play
2016-10-11T15:46:13.606Z DEBUG coordinator is Chambre
2016-10-11T15:46:13.606Z DEBUG breaking out Chambre
2016-10-11T15:46:15.068Z DEBUG No such service x-file-cifs://xxx/xxx.m4a
2016-10-11T15:46:15.072Z DEBUG No such service x-file-cifs://xxx/xxxx.m4a
2016-10-11T15:46:15.086Z DEBUG Setting repeat to all
2016-10-11T15:46:15.818Z DEBUG Setting shuffle to true
2016-10-11T15:46:15.849Z DEBUG setting volume 2 on Chambre
2016-10-11T15:46:15.897Z DEBUG replacing with playlist Dodo
2016-10-11T15:46:15.919Z DEBUG Setting crossfade to true
2016-10-11T15:46:16.018Z DEBUG found playlists
  [ 'Dodo',
  'Réveil' ]
2016-10-11T15:46:16.020Z DEBUG clearing queue
2016-10-11T15:46:16.123Z DEBUG invoking play
2016-10-11T15:46:16.146Z DEBUG No such service x-file-cifs://xxx/xxxx.m4a
2016-10-11T15:46:16.152Z DEBUG No such service x-file-cifs://xxx/xxxx.m4a
2016-10-11T15:46:16.227Z DEBUG Adding file:///jffs/settings/savedqueues.rsq#2 to queue
2016-10-11T15:46:16.324Z ERROR 
  Error
    at Object.invoke (/home/medianucenter/node-sonos-http-api-1.0.1/node_modules/sonos-discovery/lib/helpers/soap.js:94:10)
    at Player.play (/home/medianucenter/node-sonos-http-api-1.0.1/node_modules/sonos-discovery/lib/models/Player.js:379:15)
    at promise.then (/home/medianucenter/node-sonos-http-api-1.0.1/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:142:46)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-10-11T15:46:16.531Z DEBUG triggering queue mode
`

I see `2016-10-11T15:46:15.086Z DEBUG Setting repeat to all` but no effect in Sonos App when I will check if Playlist is on repeat ALL in PlayMode.

And nothing about Sleep parameter.

**Comment by jishi** [comment] 2016-10-11 16:15
I can verify that sleep seems to be missing, so the documentation is wrong. It probably worked in the last version and I forgot it when I did the rewrite. Will try to add it. 

The repeat though is very weird... I'll look into it.

**Comment by jishi** [comment] 2016-10-11 20:30
Sleep and repeat has been fixed in the master branch. If you want to upgrade, do the following:

Standing in the folder *above* of `node-sonos-http-api-1.0.1` (where `ls` would list this actual folder name)

`wget -O update.tar.gz https://api.github.com/repos/jishi/node-sonos-http-api/tarball/master`
`tar --strip-components=1 -zxf update.tar.gz -C node-sonos-http-api-1.0.1` 
`cd node-sonos-http-api-1.0.1`
`npm install --production`

now restart it the way you usually run it. Let me know how it works.

**Comment by naixra** [comment] 2016-10-12 08:22
Sleep works :-)

Repeat too, however, even if I don't put `repeat":all"` in preset file "Room1" for example, all of preset play with this parameter. When I play "Room1" preset, without `repeat:"all"` in file, it plays with "repeat all".

**Comment by jishi** [comment] 2016-10-12 12:51
This is expected behavior. If you don't explicitly specify plauyModes, it will not change them. There is no concept of "default" value and I think that is what people want, and how it works with most other properties. If you don't specify a volume, don't touch the volume. It would be weird if it would default to something obscure.

**Closed by jishi** 2016-10-12 12:51 UTC
