### ISSUE TITLE
API hammering Sonos causing playback issues

### ISSUE THREAD

**Issue by jmezach** [jishi/node-sonos-http-api#155] opened 2016-02-12 18:43 UTC
I know this is probably a long shot, but I thought I'd post it here anyway. Recently I had issues with my Sonos sytem that I didn't have before. I have a setup in the living room with a Playbar, a Sub and two play:3's as surrounds. I was experiencing intermittent drop-outs of both the surrounds and the sub. I tried removing and re-adding them but that didn't solve the problem, or even worse in some cases I couldn't even re-add them at all.

After further investigation I noticed that this API that I have installed on a Raspberry Pi was using most of the CPU, so I decided to shut it down. This didn't immediately solve the issue, but after also resetting the Sonos Bridge the problems I had have disappeared and everything seems to be working just fine again now.

I'm not exactly sure that this API had something to do with the issues I was having, but I've only recently installed it (like last weekend) and I've been having the issues since then so I guess it is somehow related. Then again, I've also had a power failure which might also be related. Perhaps though there should be some kind of back-off in order to ensure that if something isn't working properly it doesn't break the whole system.

**Comment by jishi** [comment] 2016-02-12 18:54
I'm running this full time at home, and haven't experienced similar issues. It is true that if something were to hammer the players with requests, they would start to behave weird, but the API in itself shouldn't do that because there is no retry logic. It's weird that you got a high CPU load, I have seen that once before when running it with the pm2 process manager, and had started the API using "cluster" mode. This trigger some sort of race condition, probably because of the network code (which doesn't really make any sense if running multiple processes).

Sonos support have also seen a tendency that the system reports network loops if you connect a raspberry pi directly into one of the players (and use SonosNet as it's connectivity). I'm not 100% sure why they would see it as a loop, since the raspberry pi doesn't actually create one. But I did experience some minor dropouts with this setup, even if I'm not 100% sure that it was because of the Rpi. 

Of course there could be bugs that I just haven't encountered yet, but I would need to know exactly how everything is connected, and preferrably reproducable steps. Please describe the installation of the rpi (Linux distribution, special configuration, how are you hosting the node process etc), as well as how it is connected to your network as well as how your Sonos gear and network gear are connected together. If you could draw a network topology map, that could also be useful.

**Comment by jishi** [comment] 2016-02-12 18:55
Also, if you could make a tcpdump or similar on the rpi when this occur, it would be fairly evident if my API is to blame. If you filter out traffic with dest port 1400, you would get all traffic that is intended for the Sonos players.

**Comment by jishi** [comment] 2016-05-13 22:54
No feedback, closing.

**Closed by jishi** 2016-05-13 22:54 UTC

**Comment by andreapx** [comment] 2016-11-03 09:21
I've had the same issue with PM2.
Running it without PM2 works like a charm

**Comment by jishi** [comment] 2016-11-03 09:32
@andreapx Are you running it using clustered mode or forked mode in PM2? In earlier versions PM2 defaulted to clustered mode, but newer versions use fork. Forked mode is the only working one. I'm running it with PM2 at home all the time without issues.

**Comment by andreapx** [comment] 2016-11-03 09:35
I actually don't remember! I had another RPi running in another room and I've installed it there without any problem

**Comment by andreapx** [comment] 2016-11-03 09:35
By the way, nice job!!!
