### ISSUE TITLE
Error when trying pandora

### ISSUE THREAD

**Issue by shafiqshariff** [jishi/node-sonos-http-api#307] opened 2016-09-16 04:17 UTC
Added Pandora settings to settings.json in root
Trying: /Kitchen/pandora/play/60s

Error I am getting:
{"status":"error","error":"Cannot read property 'toString' of null","stack":"TypeError: Cannot read property 'toString' of null\n    at Anesidora.request (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\node_modules\\anesidora\\anesidora.js:120:103)\n    at C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\lib\\actions\\pandora.js:45:12\n    at pandoraAPI (C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\lib\\actions\\pandora.js:44:12)\n    at C:\\Users\\shafiq\\Documents\\GitHub\\node-sonos-http-api\\lib\\actions\\pandora.js:62:19\n    at process._tickCallback (node.js:369:9)"}

**Comment by jplourde5** [comment] 2016-09-16 14:43
See if you can grab the updated pandora.js file from my recent pull request and replace the copy that you have.  It may resolve the issue and adds some new capabilities like playing the Genre Stations.  If you don't have a User station named 60s, what you currently have will not play.

**Comment by shafiqshariff** [comment] 2016-09-16 17:00
Hi there -- I did grab the pull request and get the same error. Without the pr, the node server crashes when I get this error. After, the server doesn't crash but I get this error detail in my browser.

**Comment by jplourde5** [comment] 2016-09-16 17:39
Are you getting the exact same error?  Can you add the new output since the line numbers will have changed?

If you go into the Sonos App and select Pandora, do you see a station called "60s"?

Looks like every call to Pandora may be failing.  Check your credentials closely and make sure they match exactly what you can successfully use to logon to the Pandora site with.

**Comment by shafiqshariff** [comment] 2016-09-16 22:49
Yes -- I'm getting the same error.  Actually, the lines I added in the original issue are with your new pull request (sorry for any confusion).
I tried with an exact station name match and got the same error:  http://xxx:5005/Kitchen/pandora/play/60s%20Oldies%20Radio
I just double checked my credentials by logging in again, and they seem correct.  My settings.json looks similar to the below:{    "pandora":  {        "username": "firstname_lastname@yahoo.com",        "password": "password"     }} 

    On Friday, September 16, 2016 12:39 PM, jplourde5 <notifications@github.com> wrote:
 

 Are you getting the exact same error? Can you add the new output since the line numbers will have changed?If you go into the Sonos App and select Pandora, do you see a station called "60s"?Looks like every call to Pandora may be failing. Check your credentials closely and make sure they match exactly what you can successfully use to logon to the Pandora site with.—

**Comment by jplourde5** [comment] 2016-09-20 17:53
Try the latest build that was updated yesterday and see if that fixes the problem

**Comment by shafiqshariff** [comment] 2016-09-21 15:00
I just pulled the latest build and tried again.  I get the following:
{   
   - status: "error",
   - error: "Cannot read property 'toString' of null",
   - stack: "TypeError: Cannot read property 'toString' of null at Anesidora.request (C:\Users\shafiq\Documents\GitHub\node-sonos-http-api\node_modules\anesidora\anesidora.js:120:103) at C:\Users\shafiq\Documents\GitHub\node-sonos-http-api\lib\actions\pandora.js:45:12 at pandoraAPI (C:\Users\shafiq\Documents\GitHub\node-sonos-http-api\lib\actions\pandora.js:44:12) at C:\Users\shafiq\Documents\GitHub\node-sonos-http-api\lib\actions\pandora.js:62:19 at process._tickCallback (node.js:369:9)"
}
 

    On Tuesday, September 20, 2016 7:31 PM, jplourde5 <notifications@github.com> wrote:
 

 Try the latest build that was updated yesterday and see if that fixes the problem—

**Comment by jplourde5** [comment] 2016-09-21 16:17
It appears that it does not have your Pandora password which needs to be in your settings file per the documentation.  Check that closely and make sure that it has been setup correctly.

**Comment by blulite** [comment] 2016-09-25 21:44
I'm having the same error.   I've verified username/password are correct.   Using the newest pandora.js

**Comment by jplourde5** [comment] 2016-09-26 17:27
I installed PM2 over the weekend on my RP3 and I'm now seeing the same problem.  The problem is somewhere in the encryption. 

Are you guys running PM2 or anything similar on node.js?

What version of node.js are you using?

**Comment by jplourde5** [comment] 2016-09-26 17:52
Found the problem and it is in the Anesidor encryption.js encryption routine.  It occurs when the data size is a multiple of 16, which is why it wasn't happening all of the time. I have submitted a fix and pull request.  Until the pull is accepted, you can fix the problem by inserting:

        if (padLength == PADDING_LENGTH) {
          padLength = 0;
        }

in encryption.js at line 13 right after

        var padLength = PADDING_LENGTH - (data.length % PADDING_LENGTH);

encryption.js can be found in node_modules/anesidora/

**Comment by blulite** [comment] 2016-09-26 19:46
implemented your fix and it works fine now.   thanks!

**Comment by jplourde5** [comment] 2016-09-26 19:47
The fix has now been merged.  You can delete the anesidora folder in node_modules and re-issue

npm install --production

to get the fix if you haven't performed my previous note

**Closed** 2016-09-26 20:25 UTC
