### ISSUE TITLE
Error on http://www.localhost.com:5005/zones

### ISSUE THREAD

**Issue by nixxle** [jishi/node-sonos-http-api#60] opened 2015-07-08 09:18 UTC
Clean install, fails on both Windows and Linux

/home/niels/sonos/node-sonos-http-api/lib/actions/zones.js:2
  callback(player.discovery.getZones());
                 ^
TypeError: Cannot read property 'discovery' of null
    at Object.zones (/home/niels/sonos/node-sonos-http-api/lib/actions/zones.js:2:18)
    at handleAction (/home/niels/sonos/node-sonos-http-api/lib/sonos-http-api.js:65:28)
    at HttpAPI.requestHandler (/home/niels/sonos/node-sonos-http-api/lib/sonos-http-api.js:47:5)
    at /home/niels/sonos/node-sonos-http-api/server.js:51:13
    at Server.finish (/home/niels/sonos/node-sonos-http-api/node_modules/node-static/lib/node-static.js:109:13)
    at finish (/home/niels/sonos/node-sonos-http-api/node_modules/node-static/lib/node-static.js:168:14)
    at /home/niels/sonos/node-sonos-http-api/node_modules/node-static/lib/node-static.js:142:17
    at Object.oncomplete (fs.js:107:15)

**Comment by jishi** [comment] 2015-07-08 19:32
Probably same as #54 .

It doesn't find any players, please describe how your device is connected to your network, and how your Sonos devices are connected.

There seems to be some issue with the SSDP discovery, but since I can not reproduce it, it's hard for me to fix unless I can get specific details from someone suffering from it.

**Comment by leerich** [comment] 2015-07-25 23:51
I have the same issues 4 out of 5 times.  I have 5 Sonos Connet:Amps and one Play:1.  One of the Connect:Amps is connected with an ethernet cable to the same switch of the nodejs server.

**Comment by jishi** [comment] 2015-07-26 20:06
Could you please try and do the following:

https://github.com/jishi/node-sonos-http-api/issues/58#issuecomment-125034051

and get back to me?

**Comment by leerich** [comment] 2015-08-04 15:06
I captured the packets and then I noticed that my Sonos system was on a different subnet than the node server.  I switched all of my zone players to the same subnet and now everything seems to work.  Although in the old setup all of my sonos apps had no problems finding my system.

**Comment by jishi** [comment] 2015-08-06 12:23
@leerich Nice to see your issue resolved. I'm stumped how it actually worked at all with any controller (offical or unofficial) though.

I still would like a capture from someone who suffers from this issue, if possible.

**Comment by leafgarland** [comment] 2015-09-10 11:04
I had exactly the same error message, in my case it was because sonos-discovery was using port 1901 and it was not free.

**Comment by jishi** [comment] 2015-09-10 11:19
@leafgarland It's only in OS X this is a problem, most other operating system is fine with multiple processes binds to the same UDP port. However, the builtin firewall in OS X also behaves a bit erratically with node.js.

**Comment by leafgarland** [comment] 2015-09-10 11:21
Right, thanks. Sorry, should have spotted the extra info in #53.

**Comment by jishi** [comment] 2015-12-07 20:37
Closing since it is related to some local environment. Without proper feedback, I can't fix it.

**Closed by jishi** 2015-12-07 20:37 UTC
