### ISSUE TITLE
Sleep fails if you try and set playMode on a radio stream in presets

### ISSUE THREAD

**Issue by UrbanDave** [jishi/node-sonos-http-api#197] opened 2016-05-02 13:53 UTC
I was having an issue with the sleep setting in my preset.  I was linking to a Pandora radio station and while the preset successfully starts the music, the sleep setting was not working.  Through some trial and error I had added:

playMode": "SHUFFLE"

to my preset. Once I removed the playMode from my preset, the sleep function works. I realize SHUFFLE doesn't make sense on a radio station but this preset is linked to a Sonos Favourite that I re-link to different sources from time to time that would support SHUFFLE.

I just wanted to pass this on in case anyone else is struggling with this or it may also be something that can be fixed in a future release?

**Comment by jishi** [comment] 2016-05-02 14:00
Ah, good observation. Makes sense to skip any playMode options if it is some sort of radio source. I'll keep that in mind for the next version.

**Comment by UrbanDave** [comment] 2016-05-02 14:03
Thanks, since the music was still starting I assumed Sonos was ignoring the playMode.  It took me a while to figure out it was preventing "sleep" from working.  I'm not sure what the connection is there.

**Comment by jishi** [comment] 2016-05-02 14:07
Yeah, in the beta branch this has been completely rewritten so it will be fairly easy to fix it once I can reproduce it there. The old code for support presets became a mess so I won't even bother fixing it there.  

everything in the preset needs to be done sequentially because otherwise the players complain, and some failures should be allowed why others shouldn't, it is probably a remnant from one of these exceptions.

**Comment by jishi** [comment] 2016-05-13 23:18
This is fixed in the beta. playMode has another syntax, and matches the one you get from a state call now:

```
"playMode": {
  "shuffle": true
}
```

**Closed by jishi** 2016-05-13 23:18 UTC
