### ISSUE TITLE
/saypreset not stopping music before joining rooms so a blast of whatever was playing in one room plays everywhere briefly before announcment

### ISSUE THREAD

**Issue by brettyj** [jishi/node-sonos-http-api#635] opened 2018-07-24 11:34 UTC
Hey,

Firstly, I didn't realise you'd released this, was really excited today when I found out :) 

It works well, the only issue I've found is that it doesn't pause all the music before grouping so one of the zones will play whatever it's playing around the group for a second or two before the TTS starts - it would be nice if it didn't do that.

Thanks

**Comment by jishi** [comment] 2018-07-27 08:58
Yeah, that doesn't really sound like the expected behavior. It will download the TTS audio clip before atually doing anything else, but it looks like it applies the preset first and then wait for the group to form, which can take an arbitrary amount of time. Would make sense to pause all players in the group before to avoid this behavior.

**Comment by jishi** [comment] 2018-08-01 19:45
Pushed a fix in 1.6.3 that should prevent this.

**Closed** 2018-08-01 19:44 UTC
Labels: bug
