### ISSUE TITLE
clip issue

### ISSUE THREAD

**Issue by dizzyjay** [jishi/node-sonos-http-api#389] opened 2016-11-28 19:10 UTC
hello. my apologies if this isn't the correct spot for this but i'm having an issue with the clip function; it very well could be me.  I have general usage including the "say" commands functioning without issue but when i follow the instructions for clip, it returns error JSON.  I did have to add the "clips" directory to static.  is there another setup step i'm overlooking?

- ie. of call: http://192.168.1.XXX:5005/wall%20tv/clip/grenade.mp3; RESULT: {"status":"error"}
- file is housed at: /static/clips/grenade.mp3
- Node.js version 7.0.0 on RPi 
- i have successfully connected to the wall tv zone with api and voiceRSS commands.

this is a fantastic API that has enabled me to control my audio with Alexa and vice versa by triggering Alexa with voiceRSS.  -well done, great product; I will happily donate.
dj

**Comment by jishi** [comment] 2016-11-28 21:18
I can not reproduce this. Do you have a log from the output of the program (in the console)? And have you verified that you can fetch the audio clip using 

 http://192.168.1.XXX:5005/clips/grenade.mp3 directly? This is the url that the Sonos system will use to get it.

**Comment by jishi** [comment] 2016-11-28 21:18
Could also be a good idea to verify the file permissions of the /static/clips folder and file, make sure it is readable by the user running the http-api.

**Comment by dizzyjay** [comment] 2016-11-29 03:32
The console log is {error: 'action \'clip\' not found'}
I confirmed the mp3 plays when linked to directly.

dj

On Nov 28, 2016, at 1:18 PM, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:


Could also be a good idea to verify the file permissions of the /static/clips folder and file, make sure it is readable by the user running the http-api.

**Comment by dizzyjay** [comment] 2016-11-29 16:53
i believe i know what the issue is.  i believe the .zip version of the api is not up to date; i installed downloaded the .zip file and did not use git clone.  i cloned the site and it has the newer clip action files in the /lib/actions/ directory.  when i tried running the clone version i got the error (below) but by copy/pasting the lib directory from the cloned version i was able to get the .zip version up and running.  the error below is what i get when i try to start the server on the cloned version (any ideas?):

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/home/pi/Desktop/node-sonos-http-api/lib/music_services/libraryDef.js:6:26)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/Desktop/node-sonos-http-api/lib/actions/musicSearch.js:9:20)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

**Comment by jishi** [comment] 2016-11-29 16:59
You can always download the latest master as a zip as well from here: https://github.com/jishi/node-sonos-http-api/archive/master.zip 

but I guess there is some path that isn't created at start that the libraryDef.js depends on... do you have a folder named "cache"? Or did you get a warning message saying something like:

"Could not create cache directory...."

**Comment by jishi** [comment] 2016-11-29 20:53
I did a clean checkout and it worked without a hitch. Assuming permission issues if you don't get the cache folder.

**Comment by jishi** [comment] 2016-11-29 21:07
Since this is not an issue with the code but rather your installation, I'm closing this issue for now but you can still comment if you need further assistance.

**Closed by jishi** 2016-11-29 21:07 UTC

**Comment by dizzyjay** [comment] 2016-11-29 23:59
yes. the issue is resolved and I agree it wasnt in the code, thanks!  is there a general forum for basic usage questions?  i'm getting up to speed on how to troubleshoot Node.js so i was able to follow the trace and fill in the missing pieces. Thanks again for your prompt responses.
