### ISSUE TITLE
installed on new raspi but wont startup

### ISSUE THREAD

**Issue by surrounded** [jishi/node-sonos-http-api#39] opened 2015-02-04 23:51 UTC
`npm install` seemed to have completed with no errors, but when I `node server.js` this is the response I receive:
```
pi@raspberrypi ~/node-sonos-http-api $ node server.js
no settings file found, will only use default settings
http server listening on port 5005

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/pi/node-sonos-http-api/lib/actions/'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at requirePath (/home/pi/node-sonos-http-api/node_modules/require-fu/lib/index.js:14:22)
    at /home/pi/node-sonos-http-api/node_modules/require-fu/lib/index.js:21:9
    at Array.forEach (native)
    at fuDirectory (/home/pi/node-sonos-http-api/node_modules/require-fu/lib/index.js:20:34)
    at /home/pi/node-sonos-http-api/node_modules/require-fu/lib/index.js:25:5
    at Object.<anonymous> (/home/pi/node-sonos-http-api/server.js:30:38)
```

Any ideas?

**Comment by jishi** [comment] 2015-02-05 09:28
Looks like ht has trouble locating or reading the actions directory. Du you have /home/pi/node-sonos-http-api/lib/actions/ available, and does it contain any files? it should have several .js files, corresonding to different API actions available.

How did you download it? Using git clone, or did you download it as a zip from github?

**Comment by surrounded** [comment] 2015-02-06 17:58
I installed using `git clone git://github.com/jishi/node-sonos-http-api.git` followed by `cd node-sonos-http-api` then `npm install`.  I have actually deleted the node-sonos-http-api directory and then re-installed using the same steps listed above only to have the same result both times.  

Here is the contents of the /home/pi/node-sonos-http-api/lib/actions/ directory:
![screen shot 2015-02-06 at 9 53 42 am](https://cloud.githubusercontent.com/assets/1367674/6084456/14473a4a-ade6-11e4-9d98-0f431d23b010.png)

**Comment by jishi** [comment] 2015-02-07 11:04
Hm, I can't seem to replicate this issue. Could you please verify the owner of the folders and files? Especially /home/pi/node-sonos-http-api/lib/actions/ 

You did invoke the git clone directly on a shell on the rpi, right? And not through another computer using a mounted volume (I'm just asking because of the screenshot which looks like OS X)

**Comment by surrounded** [comment] 2015-02-07 11:16
I ran `git clone git://github.com/jishi/node-sonos-http-api.git` via `ssh pi@raspberrypi.local` using terminal on my mac.

here is the file ownership info for /home/pi/node-sonos-http-api/lib/actions/:
```
pi@raspberrypi ~ $ ls -l /home/pi/node-sonos-http-api/lib/actions/
total 76
-rw-r--r-- 1 pi pi  247 Feb  4 02:09 favorite.js
-rw-r--r-- 1 pi pi  429 Feb  4 02:09 favorites.js
-rw-r--r-- 1 pi pi 1021 Feb  4 02:09 lockvolumes.js
-rw-r--r-- 1 pi pi  449 Feb  4 02:09 mute.js
-rw-r--r-- 1 pi pi  245 Feb  4 02:09 nextprevious.js
-rw-r--r-- 1 pi pi 1346 Feb  4 02:09 pauseall.js
-rw-r--r-- 1 pi pi  640 Feb  4 02:09 playlist.js
-rw-r--r-- 1 pi pi  471 Feb  4 02:09 playmode.js
-rw-r--r-- 1 pi pi  441 Feb  4 02:09 playpause.js
-rw-r--r-- 1 pi pi  810 Feb  4 02:09 preset.js
-rw-r--r-- 1 pi pi  231 Feb  4 02:09 reindex.js
-rw-r--r-- 1 pi pi 7034 Feb  4 02:09 say.js
-rw-r--r-- 1 pi pi  275 Feb  4 02:09 seek.js
-rw-r--r-- 1 pi pi  184 Feb  4 02:09 setavtransporturi.js
-rw-r--r-- 1 pi pi  929 Feb  4 02:09 sleep.js
-rw-r--r-- 1 pi pi  456 Feb  4 02:09 state.js
-rw-r--r-- 1 pi pi  306 Feb  4 02:09 volume.js
-rw-r--r-- 1 pi pi  160 Feb  4 02:09 zones.js
```
file/folder ownership info for /home/pi/node-sonos-http-api/lib/:
```
pi@raspberrypi ~ $ ls -l /home/pi/node-sonos-http-api/lib/
total 8
drwxr-xr-x 3 pi pi 4096 Feb  4 02:09 actions
-rw-r--r-- 1 pi pi 2590 Feb  4 02:09 sonos-http-api.js
```
file/folder ownership info for /home/pi/node-sonos-http-api/:
```
pi@raspberrypi ~ $ ls -l /home/pi/node-sonos-http-api/
total 32
drwxr-xr-x 4 pi pi 4096 Feb  6 09:53 lib
-rw-r--r-- 1 pi pi 1079 Feb  4 02:09 LICENSE.md
drwxr-xr-x 8 pi pi 4096 Feb  4 02:10 node_modules
-rw-r--r-- 1 pi pi  556 Feb  4 02:09 package.json
-rw-r--r-- 1 pi pi 6453 Feb  4 02:09 README.md
-rw-r--r-- 1 pi pi  689 Feb  4 02:09 server.js
drwxr-xr-x 5 pi pi 4096 Feb  4 02:10 static
```

**Comment by jishi** [comment] 2015-02-07 11:20
Which version of node? I can't seem to reproduce it and right now I have no clue on whats going on, however I'm on 0.10.26 on all my devices, and require-fu seems to require 0.10.x, which I haven't noticed before.

**Comment by surrounded** [comment] 2015-02-07 11:22
```
pi@raspberrypi ~ $ node -v
v0.10.36
```

**Comment by jishi** [comment] 2015-02-07 11:23
Hm, did you compile it yourself? Could you try the precompiled version just to rule out any issues with node?

http://nodejs.org/dist/v0.10.28/node-v0.10.28-linux-arm-pi.tar.gz

**Comment by csteenwyk** [comment] 2015-02-09 15:07
I just installed it on a raspberry pi and had no issues. One thing I had to do was the node that was included in debian was too old, so I had to download a newer one. Here are the steps I took:

* wget http://node-arm.herokuapp.com/node_latest_armhf.deb 
* sudo dpkg -i node_latest_armhf.deb
* svn co https://github.com/jishi/node-sonos-http-api/trunk ~/node-sonos-http-api
* cd node-sonos-http-api
* npm install
* npm install forever

I then created the following file in /etc/init.d/sonos

```
!/bin/sh
#/etc/init.d/sonos

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
    exec forever --sourceDir=/home/pi/node-sonos-http-api -p /opt/forever server.js
  ;;
stop)
  exec forever stop --sourceDir=/home/pi/node-sonos-http-api server.js
  ;;
*)
  echo "Usage: /etc/init.d/sonos {start|stop}"
  exit 1
  ;;
esac

exit 0
```

* chmod 755 /etc/init.d/sonos
* update-rc.d sonos defaults

**Comment by noesberger** [comment] 2015-02-15 17:07
Hi

I've used your init.d/sonos file for starting the service. But when I run "/etc/init.d/sonos start" it's not exiting from the script, the server is running but me console is blocked, when I press ctrl + c I can type in again but the service is stopped. What I'm doing wrong?
I also had to comment the first line, otherwise the script was not working.

**Comment by jishi** [comment] 2015-02-17 17:13
Cannot reproduce, no feedback returned. Closing for now.

**Closed by jishi** 2015-02-17 17:13 UTC

**Comment by mr-istian** [comment] 2015-05-25 12:30
I am experiencing the same issue, however on my Synology NAS.... Did you ever resolve this issue?

**Comment by jishi** [comment] 2015-05-25 14:02
@mr-istian Please open a separate issue, and include answers to the questions asked in this ticket there.
