### ISSUE TITLE
Leave group stops the music in both rooms

### ISSUE THREAD

**Issue by Sillec123** [jishi/node-sonos-http-api#491] opened 2017-04-22 15:56 UTC
Hey,

i will use the following function:

if Room living room is playing and motion is detected in room kitchen
then /kitchen/join/livingroom

This is working but if i wanna say:

if there is no motion in kitchen
then kitchen/leave

The speaker in kitchen is leaving the group but both rooms are paused. But what i want is that, the living rooms is playing without break. My goal is that you don't note that the group is ungroup in the living room. Only the kitchen speaker should leave the group and stopped playing.

**Comment by jishi** [comment] 2017-04-23 20:18
There were some confusion regarding the difference between `leave` and `isolate` and seems like this is a pretty good example of that.

I think it's a bug, will look at it when I have the time. I think it makes a difference which player that is the `coordinator` (basically, which player that is listed first in the group) and that depends on how you joined the players.

**Comment by Sillec123** [comment] 2017-04-24 19:31
My coordinator is always the same speaker in this case. And it keeps the right state (queue) but it is paused. 
I will have a party mode and if it is true then my living room player will always be the coordinator. If then is motion in one other room the room will join to the living room. This is working now. But If there is no motion he should leave the group. But then both are paused and the group is ungrouped. But I will play the music in the living room without any interruptions.

**Comment by jishi** [comment] 2017-05-07 19:51
I can't reproduce this. Are you sure you are actually running the latest version of the API? This was an issue a long time ago, but has since been fixed in v1.2.6 (november)

**Closed by jishi** 2017-05-07 19:51 UTC
Labels: bug
