### ISSUE TITLE
http://localhost:5005/living room/repeat/on will also set 'shuffle on'

### ISSUE THREAD

**Issue by ghost** [jishi/node-sonos-http-api#98] opened 2015-12-10 05:47 UTC
Hi,

'http://localhost:5005/living room/repeat/on' will also set 'shuffle on'
Is this programmed?

Thanks.

**Comment by jishi** [comment] 2015-12-10 08:42
Not intentionally, but the shuffle/repeat function is not separate calls but merely a tri-state variable in UPnP, so I need to know current state in order to switch to a new state depending on what you want to toggle. This probably has some glitch, if you can give me reproducable steps, it will be an easy fix. I have seen this happen intermittently, but I haven't been able to reproduce it at will.

**Comment by wallee9000** [comment] 2015-12-10 09:56
Hi Jimmy,

Thanks for your quick response.
I'm using your http-api for a agent between my HomeControl system and the Sonos system  and it is working like a charm. I installed it on my Ubuntu 14.04.1 system. Im using curl for doing the http requests but for testing im using only the Firefox browser.
After some more testing i found out some more:

- Start Windows Sonos program for shuffle and repeat status monitoring.
- Set shuffle OFF and repeat OFF with the Windows Sonos program
- http://linux7:5005/woonkamer/shuffle/on -> result: SHUFFLE ON (OK), REPEAT ON (FAULT)
- Set shuffle OFF and repeat OFF with the Windows Sonos program
- http://linux7:5005/woonkamer/repeat/on -> result: SHUFFLE ON (FAULT), REPEAT ON (OK)
THEN:
- http://linux7:5005/woonkamer/shuffle/off -> result: SHUFFLE OFF (OK), REPEAT ON (OK)
- http://linux7:5005/woonkamer/shuffle/on -> result: SHUFFLE ON (OK), REPEAT ON (OK)
- http://linux7:5005/woonkamer/repeat/off -> result: SHUFFLE ON (OK), REPEAT OFF (OK)
- http://linux7:5005/woonkamer/repeat/on -> result: SHUFFLE ON (OK), REPEAT ON (OK)

This is reproducable by me. It seems that the 'repeat' and 'shuffle' status set by the Sonos program is not read well? Only when shuffle and repeat is set OFF bij the http-api status things are ok 

Thanks.

**Comment by jishi** [comment] 2015-12-10 10:42
Okay, great feedback. I'm gonna check my system and see if the same is reproducible there when I get the time.

**Comment by wallee9000** [comment] 2015-12-10 15:02
Hi,

Please let me know if you need some more testing. 

Thanks!

**Comment by NovaGL** [comment] 2016-04-08 10:29
Hi, this is happening with me too, everytime I turn shuffle on it turns repeat on. Any update?

**Comment by wallee9000** [comment] 2016-04-08 19:19
I tested the latest version. The problem is still there.

**Comment by jishi** [comment] 2016-04-11 08:56
I think there might be some state-discrepancy when keeping track of the players. This has been completely rewritten and I'm close to finishing the new version, I will try and add some tests that identifies this behavior and verifies the functionality accordingly. 

You will have to be a bit more patient :)

**Comment by wallee9000** [comment] 2016-04-11 09:04
Hi Jimmy,

Its no big problem for me. Thank you for your effort!

**Comment by jishi** [comment] 2016-05-13 23:09
This should be fixed in the beta. Re-open if you can still reproduce it after testing the beta.

**Closed by jishi** 2016-05-13 23:09 UTC
Labels: bug
