### ISSUE TITLE
Say command and presets

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-http-api#476] opened 2017-03-20 17:08 UTC
Hi, 
I am using the presets to group a number of players together in the morning.
I then issue a different say command to each room as a morning greeting.
As I send the say command to each player, it 'leaves' group, processes the say and then rejoins.
It seems to get 'stuck' sometimes as players are leaving, processing say and getting joined back in.
I tried a short delay between the say but it doesn't seem to result in a better outcome. The only way would seem to separate them by 30 seconds but then this needs a lot of timing built in which is not ideal

If I create a group (that has a co-ordinator) should I be able to issue the say command to the coordinator and have it uttered by all members of the group or is the say a 1-1 instruction.

Thanks
-f

**Comment by jishi** [comment] 2017-03-21 09:15
Not possible today, but has been suggested and seems like a good idea.

Duplicate of https://github.com/jishi/node-sonos-http-api/issues/270

**Closed by jishi** 2017-03-21 09:15 UTC
