### ISSUE TITLE
clip/clipall playing existing track rather than requested track

### ISSUE THREAD

**Issue by adamk-everythingandroid** [jishi/node-sonos-http-api#553] opened 2017-09-29 22:54 UTC
First of all, thanks for the API, amazingly useful and simple to use. It's all working for me fine except I'm having some strange issues with clip/clipall - when I make those calls it returns "success" but repeats the mp3 already loaded on my Sonos rather than playing the one requested in the URL.

For example:
 -Sonos played "doorbell.mp3" last and it is currently in a stopped state, volume from last play was 60
 -I make a call to the API via: http://localhost:5005/living%20room/clip/bell2.mp3/30
 -Instead of bell2.mp3 playing at 30% volume, doorbell.mp3 plays again at volume 60

The same happens for clipall as well but "say" and "sayall" work as expected.

I am using Node v4.2.6.

Running the server with debug and hitting the URL as above (bell2.mp3/30) I see:
```
2017-09-29T22:44:12.830Z DEBUG backup state was
  { players: [ { roomName: 'Living Room', volume: 60 } ],
  state: 'STOPPED',
  uri: 'http://localhost/sounds/doorbell.mp3',
  metadata: '',
  playMode: { repeat: 'none' },
  trackNo: 1,
  elapsedTime: 0 }
2017-09-29T22:44:12.835Z DEBUG backup presets array
  [ { players: [ [Object] ],
    state: 'STOPPED',
    uri: 'http://localhost/sounds/doorbell.mp3',
    metadata: '',
    playMode: { repeat: 'none' },
    trackNo: 1,
    elapsedTime: 0 } ]
2017-09-29T22:44:12.838Z DEBUG coordinator is Living Room
2017-09-29T22:44:12.838Z DEBUG breaking out Living Room because player is coordinator of group and uri differs
2017-09-29T22:44:12.892Z DEBUG setting volume 30 on Living Room
2017-09-29T22:44:12.916Z DEBUG repeat: false, shuffle: undefined
2017-09-29T22:44:12.916Z DEBUG calculated playmode to NORMAL
2017-09-29T22:44:12.924Z DEBUG invoking play
2017-09-29T22:44:12.937Z DEBUG Setting restore timer for NaN ms
2017-09-29T22:44:12.940Z DEBUG 3 elapsed with NaN to spare
2017-09-29T22:44:12.940Z DEBUG exactly 1 preset left
  { players: [ { roomName: 'Living Room', volume: 60 } ],
  state: 'STOPPED',
  uri: 'http://localhost/sounds/doorbell.mp3',
  metadata: '',
  playMode: { repeat: 'none' },
  trackNo: 1,
  elapsedTime: 0 }
2017-09-29T22:44:12.941Z DEBUG applying preset
  { players: [ { roomName: 'Living Room', volume: 60 } ],
  state: 'STOPPED',
  uri: 'http://localhost/sounds/doorbell.mp3',
  metadata: '',
  playMode: { repeat: 'none' },
  trackNo: 1,
  elapsedTime: 0 }
2017-09-29T22:44:12.941Z DEBUG coordinator is Living Room
2017-09-29T22:44:13.086Z DEBUG setting volume 60 on Living Room
2017-09-29T22:44:13.132Z DEBUG repeat: none, shuffle: undefined
2017-09-29T22:44:13.132Z DEBUG calculated playmode to NORMAL
after backup preset applied []
2017-09-29T22:44:14.052Z DEBUG Player changed to state PLAYING
2017-09-29T22:44:14.052Z ERROR 
  ReferenceError: onTransportChange is not defined
    at Player.transportChange (/home/adam/sonos/node-sonos-http-api/lib/helpers/single-player-announcement.js:110:42)
    at Player.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Player.emit (events.js:169:7)
    at /home/adam/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:319:23
    at process._tickDomainCallback (node.js:411:9)
```
(note that I also have a regular http server on port 80 with sounds which is where doorbell.mp3 is located, thus the missing port 5005 in the URL)

**Comment by adamk-everythingandroid** [comment] 2017-09-30 00:32
I seem to have worked out the issue but I'm not sure how to fix. The duration is not being set here:
https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/clipall.js#L16

Therefore restoreTimeout is not set correctly (nan) here:
https://github.com/jishi/node-sonos-http-api/blob/master/lib/helpers/all-player-announcement.js#L87

And the playback basically stops immediately.

For TTS the result has the duration but I don't see a way to get the duration of a chosen clip. I have set the duration to an arbitrary high value for now and it's working.

**Comment by jishi** [comment] 2017-09-30 13:22
Yeah, I know what the cause is. The improvements I made for say/sayall
affected clip as well, but I have forgotten to implement the duration
readout.

I'll fix it as soon as I get the chance.

**Comment by adamk-everythingandroid** [comment] 2017-10-01 12:02
Amazing, thanks for the fast response.

**Comment by jishi** [comment] 2017-10-01 16:53
Pushed a fix for it now.

**Closed by jishi** 2017-10-01 16:53 UTC

**Comment by adamk-everythingandroid** [comment] 2017-10-02 11:10
Thanks! Working well now.
